@echo off
REM ============================================================================
REM Free Tier Setup Script for Windows
REM Sets up Ollama with recommended models for zero-cost MVP generation
REM ============================================================================

echo.
echo ========================================================================
echo   Second Brain Agent - Free Tier Setup
echo ========================================================================
echo.
echo This script will help you set up a 100%% FREE configuration using Ollama.
echo.
echo Requirements:
echo   - 8GB RAM minimum (16GB recommended)
echo   - 10GB free disk space
echo   - Internet connection (for initial model download)
echo.
echo Press Ctrl+C to cancel, or
pause

echo.
echo [1/5] Checking if Ollama is installed...
echo.

where ollama >nul 2>&1
if %errorlevel% neq 0 (
    echo Ollama is not installed!
    echo.
    echo Please install Ollama first:
    echo   1. Go to: https://ollama.ai/download
    echo   2. Download and install Ollama for Windows
    echo   3. Run this script again
    echo.
    pause
    exit /b 1
)

echo ✓ Ollama is installed

echo.
echo [2/5] Pulling recommended models...
echo This will download ~10GB of models. It may take 10-20 minutes.
echo.

echo Pulling qwen2.5-coder:3b (fast parsing, 2GB)...
ollama pull qwen2.5-coder:3b
if %errorlevel% neq 0 (
    echo Failed to pull qwen2.5-coder:3b
    exit /b 1
)

echo.
echo Pulling qwen2.5-coder:7b (code generation, 4GB)...
ollama pull qwen2.5-coder:7b
if %errorlevel% neq 0 (
    echo Failed to pull qwen2.5-coder:7b
    exit /b 1
)

echo.
echo Pulling llama3.2:latest (reasoning, 2GB)...
ollama pull llama3.2:latest
if %errorlevel% neq 0 (
    echo Failed to pull llama3.2:latest
    exit /b 1
)

echo.
echo ✓ All models downloaded successfully!

echo.
echo [3/5] Testing models...
echo.

echo Testing qwen2.5-coder:3b...
echo Write a hello function in Python | ollama run qwen2.5-coder:3b >nul 2>&1
if %errorlevel% equ 0 (
    echo ✓ qwen2.5-coder:3b working
) else (
    echo ✗ qwen2.5-coder:3b test failed
)

echo.
echo [4/5] Creating .env configuration...
echo.

if exist .env (
    echo .env already exists. Creating .env.free-tier instead.
    set ENV_FILE=.env.free-tier
) else (
    set ENV_FILE=.env
)

echo # Free Tier Configuration - 100%% FREE! > %ENV_FILE%
echo # Generated by setup_free_tier.bat >> %ENV_FILE%
echo. >> %ENV_FILE%
echo # Primary provider: Ollama ^(local, free^) >> %ENV_FILE%
echo LLM_PROVIDER=ollama >> %ENV_FILE%
echo OLLAMA_BASE_URL=http://localhost:11434 >> %ENV_FILE%
echo. >> %ENV_FILE%
echo # Budget mode with good quality >> %ENV_FILE%
echo BUDGET_MODE=true >> %ENV_FILE%
echo OLLAMA_PARSING_MODEL=qwen2.5-coder:3b >> %ENV_FILE%
echo OLLAMA_REASONING_MODEL=llama3.2:latest >> %ENV_FILE%
echo OLLAMA_CODING_MODEL=qwen2.5-coder:7b >> %ENV_FILE%
echo OLLAMA_REVIEW_MODEL=qwen2.5-coder:3b >> %ENV_FILE%
echo. >> %ENV_FILE%
echo # Performance optimizations >> %ENV_FILE%
echo ENABLE_PARALLEL_PARSING=true >> %ENV_FILE%
echo ENABLE_RESPONSE_CACHE=true >> %ENV_FILE%
echo CACHE_TTL_HOURS=24 >> %ENV_FILE%
echo. >> %ENV_FILE%
echo # Optional: Add Gemini free tier for TDD generation ^(best quality^) >> %ENV_FILE%
echo # Uncomment and add your Gemini API key: >> %ENV_FILE%
echo # LLM_REASONING_PROVIDER=google >> %ENV_FILE%
echo # GOOGLE_API_KEY=your_free_tier_key_here >> %ENV_FILE%
echo. >> %ENV_FILE%

echo ✓ Configuration saved to %ENV_FILE%

echo.
echo [5/5] Setup complete!
echo.
echo ========================================================================
echo   FREE TIER SETUP COMPLETE!
echo ========================================================================
echo.
echo Configuration: %ENV_FILE%
echo.
echo What you get:
echo   ✓ 100%% FREE code generation
echo   ✓ No API keys required
echo   ✓ Unlimited generations
echo   ✓ Works offline
echo   ✓ Privacy - your data never leaves your machine
echo.
echo Performance:
echo   - TDD Generation: ~2-3 minutes
echo   - Code Generation: ~1-2 minutes
echo   - Total: ~5-10 minutes per MVP
echo.
echo Next steps:
echo   1. Start the server: python app.py
echo   2. Generate your first FREE MVP!
echo.
echo Optional improvements:
echo   - Add Gemini free tier for TDD ^(edit %ENV_FILE%^)
echo   - See docs/FREE_TIER_SETUP.md for more tips
echo.
echo Cost per MVP: $0.00 🎉
echo ========================================================================
echo.

if "%ENV_FILE%"==".env.free-tier" (
    echo.
    echo NOTE: Configuration saved to .env.free-tier
    echo Your existing .env was not modified.
    echo To use this config, copy it: copy .env.free-tier .env
    echo.
)

pause