#!/bin/bash
# ============================================================================
# Free Tier Setup Script for Linux/Mac
# Sets up Ollama with recommended models for zero-cost MVP generation
# ============================================================================

set -e

echo ""
echo "========================================================================"
echo "  Second Brain Agent - Free Tier Setup"
echo "========================================================================"
echo ""
echo "This script will help you set up a 100% FREE configuration using Ollama."
echo ""
echo "Requirements:"
echo "  - 8GB RAM minimum (16GB recommended)"
echo "  - 10GB free disk space"
echo "  - Internet connection (for initial model download)"
echo ""
read -p "Press Enter to continue (Ctrl+C to cancel)..."

echo ""
echo "[1/5] Checking if Ollama is installed..."
echo ""

if ! command -v ollama &> /dev/null; then
    echo "Ollama is not installed!"
    echo ""
    echo "Please install Ollama first:"
    echo "  curl -fsSL https://ollama.ai/install.sh | sh"
    echo ""
    echo "Or visit: https://ollama.ai/download"
    echo ""
    exit 1
fi

echo "✓ Ollama is installed"

# Check if Ollama service is running
if ! ollama list &> /dev/null; then
    echo ""
    echo "Ollama service is not running. Starting it..."

    # Try to start Ollama based on OS
    if [[ "$OSTYPE" == "darwin"* ]]; then
        # macOS
        open -a Ollama 2>/dev/null || echo "Please start Ollama from Applications"
    else
        # Linux
        sudo systemctl start ollama 2>/dev/null || echo "Please start Ollama service"
    fi

    echo "Waiting for Ollama to start..."
    sleep 5
fi

echo ""
echo "[2/5] Pulling recommended models..."
echo "This will download ~10GB of models. It may take 10-20 minutes."
echo ""

echo "Pulling qwen2.5-coder:3b (fast parsing, 2GB)..."
ollama pull qwen2.5-coder:3b

echo ""
echo "Pulling qwen2.5-coder:7b (code generation, 4GB)..."
ollama pull qwen2.5-coder:7b

echo ""
echo "Pulling llama3.2:latest (reasoning, 2GB)..."
ollama pull llama3.2:latest

echo ""
echo "✓ All models downloaded successfully!"

echo ""
echo "[3/5] Testing models..."
echo ""

echo "Testing qwen2.5-coder:3b..."
if echo "Write a hello function in Python" | ollama run qwen2.5-coder:3b > /dev/null 2>&1; then
    echo "✓ qwen2.5-coder:3b working"
else
    echo "✗ qwen2.5-coder:3b test failed"
fi

echo ""
echo "[4/5] Creating .env configuration..."
echo ""

ENV_FILE=".env"
if [ -f ".env" ]; then
    echo ".env already exists. Creating .env.free-tier instead."
    ENV_FILE=".env.free-tier"
fi

cat > "$ENV_FILE" << 'EOL'
# Free Tier Configuration - 100% FREE!
# Generated by setup_free_tier.sh

# Primary provider: Ollama (local, free)
LLM_PROVIDER=ollama
OLLAMA_BASE_URL=http://localhost:11434

# Budget mode with good quality
BUDGET_MODE=true
OLLAMA_PARSING_MODEL=qwen2.5-coder:3b
OLLAMA_REASONING_MODEL=llama3.2:latest
OLLAMA_CODING_MODEL=qwen2.5-coder:7b
OLLAMA_REVIEW_MODEL=qwen2.5-coder:3b

# Performance optimizations
ENABLE_PARALLEL_PARSING=true
ENABLE_RESPONSE_CACHE=true
CACHE_TTL_HOURS=24

# Optional: Add Gemini free tier for TDD generation (best quality)
# Uncomment and add your Gemini API key:
# LLM_REASONING_PROVIDER=google
# GOOGLE_API_KEY=your_free_tier_key_here
EOL

echo "✓ Configuration saved to $ENV_FILE"

echo ""
echo "[5/5] Setup complete!"
echo ""
echo "========================================================================"
echo "  FREE TIER SETUP COMPLETE!"
echo "========================================================================"
echo ""
echo "Configuration: $ENV_FILE"
echo ""
echo "What you get:"
echo "  ✓ 100% FREE code generation"
echo "  ✓ No API keys required"
echo "  ✓ Unlimited generations"
echo "  ✓ Works offline"
echo "  ✓ Privacy - your data never leaves your machine"
echo ""
echo "Performance:"
echo "  - TDD Generation: ~2-3 minutes"
echo "  - Code Generation: ~1-2 minutes"
echo "  - Total: ~5-10 minutes per MVP"
echo ""
echo "Next steps:"
echo "  1. Start the server: python app.py"
echo "  2. Generate your first FREE MVP!"
echo ""
echo "Optional improvements:"
echo "  - Add Gemini free tier for TDD (edit $ENV_FILE)"
echo "  - See docs/FREE_TIER_SETUP.md for more tips"
echo ""
echo "Cost per MVP: \$0.00 🎉"
echo "========================================================================"
echo ""

if [ "$ENV_FILE" == ".env.free-tier" ]; then
    echo ""
    echo "NOTE: Configuration saved to .env.free-tier"
    echo "Your existing .env was not modified."
    echo "To use this config: cp .env.free-tier .env"
    echo ""
fi