# Generated by Second Brain Agent on 2025-12-08 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True))),
                ('username', models.CharField(max_length=50, unique=True))),
                ('email', models.CharField(max_length=100, unique=True))),
                ('password_hash', models.CharField(max_length=255))),
                ('first_name', models.CharField(max_length=100, null=True, blank=True))),
                ('last_name', models.CharField(max_length=100, null=True, blank=True))),
                ('is_active', models.BooleanField(null=True, blank=True, default=True))),
                ('is_admin', models.BooleanField(null=True, blank=True, default=False))),
                ('created_at', models.DateTimeField(null=True, blank=True, default='now'))),
                ('updated_at', models.DateTimeField(null=True, blank=True))),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.IntegerField(primary_key=True))),
                ('title', models.CharField(max_length=200))),
                ('slug', models.CharField(max_length=200, unique=True))),
                ('content', models.TextField(null=True, blank=True))),
                ('excerpt', models.CharField(max_length=500, null=True, blank=True))),
                ('user_id', models.ForeignKey('user', on_delete=models.CASCADE))),
                ('published', models.BooleanField(null=True, blank=True, default=False))),
                ('view_count', models.IntegerField(null=True, blank=True, default=0))),
                ('created_at', models.DateTimeField(null=True, blank=True, default='now'))),
                ('updated_at', models.DateTimeField(null=True, blank=True))),
            ],
            options={
                'db_table': 'post',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.IntegerField(primary_key=True))),
                ('post_id', models.ForeignKey('post', on_delete=models.CASCADE))),
                ('user_id', models.ForeignKey('user', on_delete=models.CASCADE))),
                ('content', models.TextField())),
                ('approved', models.BooleanField(null=True, blank=True, default=False))),
                ('created_at', models.DateTimeField(null=True, blank=True, default='now'))),
            ],
            options={
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.IntegerField(primary_key=True))),
                ('name', models.CharField(max_length=50, unique=True))),
                ('slug', models.CharField(max_length=50, unique=True))),
                ('created_at', models.DateTimeField(null=True, blank=True, default='now'))),
            ],
            options={
                'db_table': 'tag',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='idx_user_email'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['title'], name='idx_post_title'),
        ),
    ]
